package application;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

import javafx.scene.image.ImageView;

import javafx.scene.input.KeyEvent;

public class MainController {
	@FXML
	private ImageView logoImage;
	@FXML
	private TextArea rkInputBox;
	@FXML
	private TextArea myInputBox;

	// Event Listener on TextArea[#rkInputBox].onKeyTyped
	@FXML
	public void onRKKeyTyped(KeyEvent event) {
		// TODO Autogenerated
//		Stage mainWindow = (Stage) rkInputBox.getScene().getWindow();
		String title = rkInputBox.getText();
		myInputBox.setText(title);
//		mainWindow.setTitle(title);
	}

	// Event Listener on TextArea[#myInputBox].onKeyTyped
	@FXML
	public void onMYKeyTyped(KeyEvent event) {
		// TODO Autogenerated
//		Stage mainWindow = (Stage) rkInputBox.getScene().getWindow();
		String title = myInputBox.getText();
		rkInputBox.setText(title);
//		mainWindow.setTitle(title);
	}

	// Event Listener on Button.onAction
	@FXML
	public void onClickCopyRK(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button.onAction
	@FXML
	public void onClickCopyALL(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button.onAction
	@FXML
	public void onClickCopyMY(ActionEvent event) {
		// TODO Autogenerated
	}
}
